version: '3.7'

services:

  web:
    tty: true
    stdin_open: true
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - docker.env/development/web
      - docker.env/development/database

  database:
    image: postgres
    env_file:
      - docker.env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: